version = 0.1

[default.deploy.parameters]
stack_name = "wordlecracker"
resolve_s3 = true
s3_prefix = "wordlecracker"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "ap-southeast-2"
